[window]
decorations = "None"
opacity = 0.95

[scrolling]
history = 1000
multiplier = 5

[font]
# normal = { family = "monospace", style = "Regular" }
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 12

[env]
TERM = "xterm-256color"
