include color_scheme.conf
include fonts.conf
include os_tweaks.conf
include scrollback.conf
include terminal_bell.conf
include text_cursor.conf
include window_layout.conf

# Advanced
clipboard_control write-clipboard write-primary no-append
